 # schema.yml

version: 2

sources:
   - name: gz_raw_data
     database: eco-signal-479210-b6
     schema: gz_raw_data
     loader: bigquery
     description: test
     freshness:
       warn_after: {count: 12, period: hour}
       error_after: {count: 24, period: hour}
     tables:
       - name: sales
         identifier: raw_gz_sales
         description: sales of Greenweez / we have on row per product_id found in each orders_id
         loaded_at_field: date_date
         columns:
           - name: date_date
             description: date of purchase
           - name: orders_id
             description: ID of the order
           - name: pdt_id
             description: ID of the product
           - name: revenue
             description: Order revenue
           - name: quantity
             description: quantity per product per Order 
         tests:
           - unique: 
              column_name: "(orders_id || '-' || pdt_id)"
             
                
                          
       - name: product
         identifier: raw_gz_product
         description: The price each product_id cost in purchase_price
         columns:
           - name: products_id
             description: ID of the product, primary key
             tests:
              - unique
              - not_null
           - name: purchase_price
             description: Selling price of each product
                    
                    
       - name: ship
         identifier: raw_gz_ship
         description: shipping at Greenweez
         columns:
          - name: orders_id
            description: id of the each order
            tests:
             - unique
             - not_null
          - name: shipping_fee
            description: the cost of the shipping
          - name: logcost
            description: the cost of all logistics for each order
          - name: ship_cost
            description: the cost of each product shipping
         
              
       - name: adwords
         identifier: raw_gz_adwords
         description: Ads using adwords
         loaded_at_field: date_date
         columns:
          - name: date_date
            description: date where the Ads was run
          - name: paid_source
            description: Where the Ads was placed, in this case all are Adwords
          - name: campaign_key
            description: primary key
          - name: camPGN_name
            description: Campaign name
          - name: ads_cost
            description: Cost of the Ads
          - name: impression
            description: nb of impressions
          - name: click
            description: nb of clicks                   

       - name: bing
         identifier: raw_gz_bing
         description: Ads Bing Ads cost, impressions and daily clicks.
         loaded_at_field: date_date
         columns:
          - name: date_date
            description: date where the Ads was run
          - name: paid_source
            description: Where the Ads was placed, in this case all are Bing
          - name: campaign_key
            description: primary key
          - name: camPGN_name
            description: Campaign name
          - name: ads_cost
            description: Cost of the Ads
          - name: impression
            description: nb of impressions
          - name: click
            description: nb of clicks  

       - name: criteo
         identifier: raw_gz_criteo
         description: Ads Criteo cost, impressions, clicks.
         loaded_at_field: date_date
         columns:
          - name: date_date
            description: date where the Ads was run
          - name: paid_source
            description: Where the Ads was placed, in this case all are Criteo
          - name: campaign_key
            description: primary key
          - name: camPGN_name
            description: Campaign name
          - name: ads_cost
            description: Cost of the Ads
          - name: impression
            description: nb of impressions
          - name: click
            description: nb of clicks  

       - name: facebook
         identifier: raw_gz_facebook
         description: Ads Facebook Ads cost, impressions, clicks.
         loaded_at_field: date_date
         columns:
          - name: date_date
            description: date where the Ads was run
          - name: paid_source
            description: Where the Ads was placed, in this case all are Facebook
          - name: campaign_key
            description: primary key
          - name: camPGN_name
            description: Campaign name
          - name: ads_cost
            description: Cost of the Ads
          - name: impression
            description: nb of impressions
          - name: click
            description: nb of clicks 