 # schema.yml

version: 2

sources:
   - name: gz_raw_data
     database: eco-signal-479210-b6
     schema: gz_raw_data
     loader: bigquery
     description: test
     freshness:
       warn_after: {count: 12, period: hour}
       error_after: {count: 24, period: hour}
     tables:
       - name: sales
         identifier: raw_gz_sales
         description: sales of Greenweez / we have on row per product_id found in each orders_id
         loaded_at_field: date_date
         columns:
           - name: date_date
             description: date of purchase
           - name: orders_id
             description: ID of the order
           - name: pdt_id
             description: ID of the product
           - name: revenue
             description: Order revenue
           - name: quantity
             description: quantity per product per Order 
         tests:
           - unique: 
              column_name: "(orders_id || '-' || pdt_id)"
             
                
                          
       - name: product
         identifier: raw_gz_product
         description: The price each product_id cost in purchase_price
         columns:
           - name: products_id
             description: ID of the product, primary key
             tests:
              - unique
              - not_null
           - name: purchase_price
             description: Selling price of each product
                    
                    
       - name: ship
         identifier: raw_gz_ship
         description: shipping at Greenweez
         columns:
          - name: orders_id
            description: id of the each order
            tests:
             - unique
             - not_null
          - name: shipping_fee
            description: the cost of the shipping
          - name: logcost
            description: the cost of all logistics for each order
          - name: ship_cost
            description: the cost of each product shipping
         
              
           